In [33]:
import pandas as pd
import numpy as np
from six.moves import urllib
import os
import warnings
warnings.filterwarnings("ignore")

In [34]:
data_dir = "./data/"
os.makedirs(data_dir, exist_ok=True)

data_urls = ("https://raw.githubusercontent.com/mohitmahi004/atliq_hotels_data/refs/heads/main/dim_date.csv",
             "https://raw.githubusercontent.com/mohitmahi004/atliq_hotels_data/refs/heads/main/dim_hotels.csv",
             "https://raw.githubusercontent.com/mohitmahi004/atliq_hotels_data/refs/heads/main/dim_rooms.csv",
             "https://raw.githubusercontent.com/mohitmahi004/atliq_hotels_data/refs/heads/main/fact_aggregated_bookings.csv",
             "https://raw.githubusercontent.com/mohitmahi004/atliq_hotels_data/refs/heads/main/fact_bookings.csv")

for data_url in data_urls:
    print("____"*50)
    filename = os.path.basename(data_url)
    print(f"Downloading : {filename}")

    filepath = os.path.join(data_dir, filename)
    print(f"Saving at : {filepath}")

    urllib.request.urlretrieve(data_url,filepath)
    print("Downloading completed")

________________________________________________________________________________________________________________________________________________________________________________________________________
Downloading : dim_date.csv
Saving at : ./data/dim_date.csv
Downloading completed
________________________________________________________________________________________________________________________________________________________________________________________________________
Downloading : dim_hotels.csv
Saving at : ./data/dim_hotels.csv
Downloading completed
________________________________________________________________________________________________________________________________________________________________________________________________________
Downloading : dim_rooms.csv
Saving at : ./data/dim_rooms.csv
Downloading completed
________________________________________________________________________________________________________________________________________________________________________________________________________
Downloading : fact_aggregated_bookings.csv
Saving at : ./data/fact_aggregated_bookings.csv
Downloading completed
________________________________________________________________________________________________________________________________________________________________________________________________________
Downloading : fact_bookings.csv
Saving at : ./data/fact_bookings.csv
Downloading completed

In [35]:
df_dim_date = pd.read_csv("./data/dim_date.csv")
df_dim_date

         date  mmm yy week no  day_type
0   01-May-22  May 22    W 19   weekend
1   02-May-22  May 22    W 19  weekeday
2   03-May-22  May 22    W 19  weekeday
3   04-May-22  May 22    W 19  weekeday
4   05-May-22  May 22    W 19  weekeday
..        ...     ...     ...       ...
87  27-Jul-22  Jul 22    W 31  weekeday
88  28-Jul-22  Jul 22    W 31  weekeday
89  29-Jul-22  Jul 22    W 31  weekeday
90  30-Jul-22  Jul 22    W 31   weekend
91  31-Jul-22  Jul 22    W 32   weekend

[92 rows x 4 columns]

In [36]:
df_dim_date.info()

<class 'pandas.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      92 non-null     str
 1   mmm yy    92 non-null     str
 2   week no   92 non-null     str
 3   day_type  92 non-null     str
dtypes: str(4)
memory usage: 3.0 KB

In [37]:
df_dim_date.isnull().sum()

date        0
mmm yy      0
week no     0
day_type    0
dtype: int64

In [38]:
df_dim_date['date'] = pd.to_datetime(df_dim_date["date"])

In [39]:
df_dim_date.dtypes

date        datetime64[us]
mmm yy                 str
week no                str
day_type               str
dtype: object

In [40]:
df_dim_hotels = pd.read_csv("./data/dim_hotels.csv")
df_dim_hotels

    property_id  property_name  category       city
0         16558   Atliq Grands    Luxury      Delhi
1         16559  Atliq Exotica    Luxury     Mumbai
2         16560     Atliq City  Business      Delhi
3         16561      Atliq Blu    Luxury      Delhi
4         16562      Atliq Bay    Luxury      Delhi
5         16563   Atliq Palace  Business      Delhi
6         17558   Atliq Grands    Luxury     Mumbai
7         17559  Atliq Exotica    Luxury     Mumbai
8         17560     Atliq City  Business     Mumbai
9         17561      Atliq Blu    Luxury     Mumbai
10        17562      Atliq Bay    Luxury     Mumbai
11        17563   Atliq Palace  Business     Mumbai
12        18558   Atliq Grands    Luxury  Hyderabad
13        18559  Atliq Exotica    Luxury  Hyderabad
14        18560     Atliq City  Business  Hyderabad
15        18561      Atliq Blu    Luxury  Hyderabad
16        18562      Atliq Bay    Luxury  Hyderabad
17        18563   Atliq Palace  Business  Hyderabad
18        19558   Atliq Grands    Luxury  Bangalore
19        19559  Atliq Exotica    Luxury  Bangalore
20        19560     Atliq City  Business  Bangalore
21        19561      Atliq Blu    Luxury  Bangalore
22        19562      Atliq Bay    Luxury  Bangalore
23        19563   Atliq Palace  Business  Bangalore
24        17564  Atliq Seasons  Business     Mumbai

In [41]:
df_dim_hotels.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_id    25 non-null     int64
 1   property_name  25 non-null     str
 2   category       25 non-null     str
 3   city           25 non-null     str
dtypes: int64(1), str(3)
memory usage: 932.0 bytes

In [42]:
df_dim_hotels.isnull().sum()

property_id      0
property_name    0
category         0
city             0
dtype: int64

In [43]:
df_dim_rooms = pd.read_csv("./data/dim_rooms.csv")
df_dim_rooms

  room_id    room_class
0     RT1      Standard
1     RT2         Elite
2     RT3       Premium
3     RT4  Presidential

In [44]:
df_dim_rooms.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   room_id     4 non-null      str
 1   room_class  4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [45]:
df_fact_aggregated_bookings = pd.read_csv("./data/fact_aggregated_bookings.csv")
df_fact_aggregated_bookings

      property_id check_in_date room_category  successful_bookings  capacity
0           16559     01-May-22           RT1                   25        30
1           19562     01-May-22           RT1                   28        30
2           19563     01-May-22           RT1                   23        30
3           17558     01-May-22           RT1                   13        19
4           16558     01-May-22           RT1                   18        19
...           ...           ...           ...                  ...       ...
9195        16563     31-Jul-22           RT4                   13        18
9196        16559     31-Jul-22           RT4                   13        18
9197        17558     31-Jul-22           RT4                    3         6
9198        19563     31-Jul-22           RT4                    3         6
9199        17561     31-Jul-22           RT4                    3         4

[9200 rows x 5 columns]

In [46]:
df_fact_aggregated_bookings.info()

<class 'pandas.DataFrame'>
RangeIndex: 9200 entries, 0 to 9199
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   property_id          9200 non-null   int64
 1   check_in_date        9200 non-null   str
 2   room_category        9200 non-null   str
 3   successful_bookings  9200 non-null   int64
 4   capacity             9200 non-null   int64
dtypes: int64(3), str(2)
memory usage: 359.5 KB

In [47]:
df_fact_aggregated_bookings['check_in_date']= pd.to_datetime(df_fact_aggregated_bookings['check_in_date'])

In [48]:
df_fact_aggregated_bookings

      property_id check_in_date room_category  successful_bookings  capacity
0           16559    2022-05-01           RT1                   25        30
1           19562    2022-05-01           RT1                   28        30
2           19563    2022-05-01           RT1                   23        30
3           17558    2022-05-01           RT1                   13        19
4           16558    2022-05-01           RT1                   18        19
...           ...           ...           ...                  ...       ...
9195        16563    2022-07-31           RT4                   13        18
9196        16559    2022-07-31           RT4                   13        18
9197        17558    2022-07-31           RT4                    3         6
9198        19563    2022-07-31           RT4                    3         6
9199        17561    2022-07-31           RT4                    3         4

[9200 rows x 5 columns]

In [49]:
df_fact_bookings = pd.read_csv("./data/fact_bookings.csv")
df_fact_bookings

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized
0,May012216558RT11,16558,2022-04-27,2022-05-01,2022-05-02,3,RT1,direct online,1.0,Checked Out,10010,10010
1,May012216558RT12,16558,2022-04-30,2022-05-01,2022-05-02,2,RT1,others,NaN,Cancelled,9100,3640
2,May012216558RT13,16558,2022-04-28,2022-05-01,2022-05-04,2,RT1,logtrip,5.0,Checked Out,9100,9100
3,May012216558RT14,16558,2022-04-28,2022-05-01,2022-05-02,2,RT1,others,NaN,Cancelled,9100,3640
4,May012216558RT15,16558,2022-04-27,2022-05-01,2022-05-02,4,RT1,direct online,5.0,Checked Out,10920,10920
...,...,...,...,...,...,...,...,...,...,...,...,...
134585,Jul312217564RT46,17564,2022-07-29,2022-07-31,2022-08-03,1,RT4,makeyourtrip,2.0,Checked Out,32300,32300
134586,Jul312217564RT47,17564,2022-07-30,2022-07-31,2022-08-01,4,RT4,logtrip,2.0,Checked Out,38760,38760
134587,Jul312217564RT48,17564,2022-07-30,2022-07-31,2022-08-02,1,RT4,tripster,NaN,Cancelled,32300,12920
134588,Jul312217564RT49,17564,2022-07-29,2022-07-31,2022-08-01,2,RT4,logtrip,2.0,Checked Out,32300,32300
134589,Jul312217564RT410,17564,2022-07-31,2022-07-31,2022-08-01,2,RT4,makeyourtrip,NaN,Cancelled,32300,12920

In [50]:
df_fact_bookings.info()

<class 'pandas.DataFrame'>
RangeIndex: 134590 entries, 0 to 134589
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   booking_id         134590 non-null  str
 1   property_id        134590 non-null  int64
 2   booking_date       134590 non-null  str
 3   check_in_date      134590 non-null  str
 4   checkout_date      134590 non-null  str
 5   no_guests          134590 non-null  int64
 6   room_category      134590 non-null  str
 7   booking_platform   134590 non-null  str
 8   ratings_given      56683 non-null   float64
 9   booking_status     134590 non-null  str
 10  revenue_generated  134590 non-null  int64
 11  revenue_realized   134590 non-null  int64
dtypes: float64(1), int64(4), str(7)
memory usage: 12.3 MB

In [51]:
df_fact_bookings['check_in_date']= pd.to_datetime(df_fact_bookings['check_in_date'])
df_fact_bookings['booking_date']= pd.to_datetime(df_fact_bookings['booking_date'])
df_fact_bookings['checkout_date']= pd.to_datetime(df_fact_bookings['checkout_date'])

In [52]:
df_fact_bookings.info()

<class 'pandas.DataFrame'>
RangeIndex: 134590 entries, 0 to 134589
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   booking_id         134590 non-null  str
 1   property_id        134590 non-null  int64
 2   booking_date       134590 non-null  datetime64[us]
 3   check_in_date      134590 non-null  datetime64[us]
 4   checkout_date      134590 non-null  datetime64[us]
 5   no_guests          134590 non-null  int64
 6   room_category      134590 non-null  str
 7   booking_platform   134590 non-null  str
 8   ratings_given      56683 non-null   float64
 9   booking_status     134590 non-null  str
 10  revenue_generated  134590 non-null  int64
 11  revenue_realized   134590 non-null  int64
dtypes: datetime64[us](3), float64(1), int64(4), str(4)
memory usage: 12.3 MB

In [56]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://{user}:{pw}@localhost:3306/{db}".format(user='root', pw='0509', db='hotel_rev_insights_db'))

In [57]:
df_dim_date.to_sql(con=engine, name="dim_date", index=False, if_exists='replace')

OperationalError: (pymysql.err.OperationalError) (1049, "Unknown database 'hotel_rev_insights_db'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)